import {Input} from './input.js';
import {AudioManager} from './audio.js';
import {ParticleSystem} from './particles.js';
import {Player,Enemy,Gem} from './entities.js';
import {createWave} from './levels.js';
import {UI} from './ui.js';

const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');let W=innerWidth,H=innerHeight;
function resize(){W=innerWidth;H=innerHeight;canvas.width=W;canvas.height=H}addEventListener('resize',resize);resize();
const input=new Input(canvas),audio=new AudioManager(),particles=new ParticleSystem(),ui=new UI();let state='menu',run=null,last=0,acc=0,shake=0,flash=0,time=0;
const upgradePool=[
 {id:'power',title:'HEAVY SNAP',desc:'Snap damage +1. Enemies burst into bigger fragments.'},
 {id:'rapid',title:'QUICK FINGERS',desc:'Snap cooldown reduced by 25%. Chain your shots.'},
 {id:'range',title:'LONG REACH',desc:'Snap range increased by 32%. Control the arena.'},
 {id:'vitality',title:'WARM CORE',desc:'Max vitality +30 and recover 30 vitality.'},
 {id:'magnet',title:'POLAR MAGNET',desc:'Pull crystals from twice as far away.'},
 {id:'stride',title:'ICE RUNNER',desc:'Movement speed increased by 22%.'}
];
function best(){return JSON.parse(localStorage.getItem('polarBest')||'{"wave":0,"score":0}')}
function saveBest(){const b=best();if(run.score>b.score||run.wave>b.wave)localStorage.setItem('polarBest',JSON.stringify({wave:Math.max(b.wave,run.wave),score:Math.max(b.score,run.score)}))}
function start(){audio.unlock();audio.click();input.reset();run={wave:1,score:0,player:new Player(W/2,H/2),enemies:[],gems:[],queue:createWave(1,W,H),queueIndex:0,spawnWait:0,pulses:[],hitstop:0};state='playing';ui.playing();particles.items=[];flash=.25}
function menu(){state='menu';input.reset();ui.title(best());audio.click()}
function pause(){if(state==='playing'){state='pause';ui.pause();audio.click()}else if(state==='pause'){state='playing';ui.playing();audio.click()}}
function finish(win=false){saveBest();state=win?'win':'over';ui.result(win?ui.panels.win:ui.panels.over,run.score,run.wave,best());audio[win?'clear':'hurt']();run.pulses=[]}
function chooseUpgrade(o){audio.click();const p=run.player;if(o.id==='power')p.snapDamage++;if(o.id==='rapid')p.snapCooldown*=.75;if(o.id==='range')p.snapRange*=1.32;if(o.id==='vitality'){p.maxHealth+=30;p.health=Math.min(p.maxHealth,p.health+30)}if(o.id==='magnet')p.magnet*=2;if(o.id==='stride')p.speed*=1.22;run.wave++;run.queue=createWave(run.wave,W,H);run.queueIndex=0;run.spawnWait=0;state='playing';ui.playing();particles.burst(p.x,p.y,'#7beeff',35,230);flash=.2}
ui.onStart=start;ui.onRetry=start;ui.onResume=pause;ui.onMenu=menu;ui.onUpgrade=chooseUpgrade;ui.onPause=pause;ui.onSound=()=>ui.soundLabel(audio.toggle());ui.soundLabel(audio.muted);ui.title(best());
function spawn(){const q=run.queue[run.queueIndex];run.enemies.push(new Enemy(q.x,q.y,q.type,run.wave));run.queueIndex++;audio.tone(180,.06,'sine',.025);particles.spark(q.x,q.y,q.type==='brute'?'#ff557d':'#72eaff',7)}
function snap(){const p=run.player,aim=p.aim(input,run.enemies);p.cooldown=p.snapCooldown;run.pulses.push({x:p.x,y:p.y,angle:Math.atan2(aim.y,aim.x),r:15,max:p.snapRange,life:.28});audio.snap();shake=Math.max(shake,7);flash=.12;let hits=0;for(let i=run.enemies.length-1;i>=0;i--){const e=run.enemies[i],dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy)||1,dot=(dx*aim.x+dy*aim.y)/d;if(d<=p.snapRange+e.r&&dot>.05){const dead=e.hit(p.snapDamage,dx/d*350,dy/d*350);hits++;particles.spark(e.x,e.y,'#ff8ebd',dead?14:6);if(dead){run.score+=e.type==='brute'?100:e.type==='dasher'?55:30;run.gems.push(new Gem(e.x,e.y));run.enemies.splice(i,1);audio.hit()}else audio.tone(260,.05,'square',.05)}}if(hits)run.hitstop=.045}
function update(dt){if(state!=='playing'||!run)return;if(run.hitstop>0){run.hitstop-=dt;particles.update(dt);return}const p=run.player;p.update(input,dt,W,H);if(input.consumeAttack()&&p.cooldown<=0)snap();if(run.queueIndex<run.queue.length){run.spawnWait-=dt;if(run.spawnWait<=0){spawn();run.spawnWait=run.queue[run.queueIndex]?.delay||.4}}for(const e of run.enemies)e.update(p,dt);for(let i=run.enemies.length-1;i>=0;i--){const e=run.enemies[i],dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d<p.r+e.r){if(p.hurt(e.damage)){p.vx=dx/d*260;p.vy=dy/d*260;particles.burst(p.x,p.y,'#ff557d',18,190);audio.hurt();shake=14;flash=.25}e.knockX=-dx/d*250;e.knockY=-dy/d*250}}for(let i=run.gems.length-1;i>=0;i--){const g=run.gems[i];g.update(dt);const dx=p.x-g.x,dy=p.y-g.y,d=Math.hypot(dx,dy);if(d<90*p.magnet){g.x+=dx/d*300*dt;g.y+=dy/d*300*dt}if(d<p.r+g.r+5){run.score+=15;run.gems.splice(i,1);particles.burst(g.x,g.y,'#ffe477',10,130);audio.pickup()}}for(let i=run.pulses.length-1;i>=0;i--){const q=run.pulses[i];q.life-=dt;q.r+=(q.max-q.r)*dt*16;if(q.life<=0)run.pulses.splice(i,1)}particles.update(dt);shake*=Math.pow(.002,dt);flash=Math.max(0,flash-dt);if(p.health<=0){finish(false);return}if(run.queueIndex>=run.queue.length&&run.enemies.length===0){if(run.wave>=8)finish(true);else{state='upgrade';audio.clear();const shuffled=[...upgradePool].sort(()=>Math.random()-.5);ui.upgrade(shuffled.slice(0,3));particles.burst(p.x,p.y,'#7beeff',45,250)}}ui.update(run.wave,run.score,p.health,p.maxHealth)}
function drawBackground(){const g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#071739');g.addColorStop(.5,'#08102a');g.addColorStop(1,'#160b2d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='#5ab9dd12';ctx.lineWidth=1;const grid=48,off=(time*12)%grid;for(let x=-grid+off;x<W+grid;x+=grid){ctx.beginPath();ctx.moveTo(x,58);ctx.lineTo(x,H);ctx.stroke()}for(let y=58-off;y<H;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#8eeeff';for(let i=0;i<35;i++){const x=(i*193)%W,y=72+(i*89)%Math.max(1,H-72);ctx.globalAlpha=.18+(i%4)*.08;ctx.fillRect(x,y,1,1)}ctx.globalAlpha=1}
function draw(){drawBackground();if(!run)return;ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);for(const g of run.gems)g.draw(ctx);for(const e of run.enemies)e.draw(ctx);for(const q of run.pulses){ctx.save();ctx.translate(q.x,q.y);ctx.rotate(q.angle);ctx.globalAlpha=Math.max(0,q.life/.28);ctx.strokeStyle='#d5fbff';ctx.shadowBlur=22;ctx.shadowColor='#4deaff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,q.r,-.95,.95);ctx.stroke();ctx.restore()}particles.draw(ctx);const aim=run.player.aim(input,run.enemies);run.player.draw(ctx,aim,time);ctx.restore();if(flash>0){ctx.fillStyle=`rgba(205,249,255,${flash*.35})`;ctx.fillRect(0,0,W,H)}const v=ctx.createRadialGradient(W/2,H/2,Math.min(W,H)*.25,W/2,H/2,Math.max(W,H)*.75);v.addColorStop(0,'transparent');v.addColorStop(1,'rgba(0,0,15,.45)');ctx.fillStyle=v;ctx.fillRect(0,0,W,H)}
function loop(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;time+=dt;if(input.consumePause())pause();acc+=dt;while(acc>=1/60){update(1/60);acc-=1/60}draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);