export class UI {
  constructor(){this.panels={title:document.getElementById('titlePanel'),pause:document.getElementById('pausePanel'),upgrade:document.getElementById('upgradePanel'),over:document.getElementById('gameOverPanel'),win:document.getElementById('winPanel')};this.hud=document.getElementById('hud');this.mobile=document.getElementById('mobileControls');this.onStart=()=>{};this.onResume=()=>{};this.onMenu=()=>{};this.onRetry=()=>{};this.onUpgrade=()=>{};document.getElementById('startButton').onclick=()=>this.onStart();document.getElementById('resumeButton').onclick=()=>this.onResume();document.getElementById('pauseMenuButton').onclick=()=>this.onMenu();document.getElementById('retryButton').onclick=()=>this.onRetry();document.getElementById('gameOverMenuButton').onclick=()=>this.onMenu();document.getElementById('winRetryButton').onclick=()=>this.onRetry();document.getElementById('winMenuButton').onclick=()=>this.onMenu();document.getElementById('pauseButton').onclick=()=>this.onPause?.();document.getElementById('soundButton').onclick=()=>this.onSound?.()}
  hideAll(){Object.values(this.panels).forEach(p=>p.classList.add('hidden'))}
  title(best){this.hideAll();this.panels.title.classList.remove('hidden');this.hud.classList.add('hidden');document.getElementById('menuBest').textContent=`WAVE ${best.wave} · ${best.score}`}
  playing(){this.hideAll();this.hud.classList.remove('hidden');this.mobile.classList.remove('hidden')}
  pause(){this.panels.pause.classList.remove('hidden')}
  upgrade(options){this.panels.upgrade.classList.remove('hidden');const box=document.getElementById('upgradeChoices');box.innerHTML='';options.forEach(o=>{const b=document.createElement('button');b.className='upgradeCard';b.innerHTML=`<b>${o.title}</b><span>${o.desc}</span>`;b.onclick=()=>this.onUpgrade(o);box.appendChild(b)})}
  result(panel,score,wave,best){this.hideAll();panel.classList.remove('hidden');this.hud.classList.add('hidden');document.getElementById(panel===this.panels.win?'winStats':'gameOverStats').innerHTML=`WAVE <b>${wave}</b><br>SCORE <b>${score}</b><br>BEST <b>WAVE ${best.wave} · ${best.score}</b>`}
  update(wave,score,health,max){document.getElementById('waveValue').textContent=wave;document.getElementById('scoreValue').textContent=score;document.getElementById('healthBar').style.width=Math.max(0,health/max*100)+'%'}
  soundLabel(muted){document.getElementById('soundButton').textContent=muted?'SOUND: OFF':'SOUND: ON'}
}