export function circleHit(a,b){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<(a.r+b.r)*(a.r+b.r)}
export function circleRect(c,rect){const x=Math.max(rect.x,Math.min(c.x,rect.x+rect.w)),y=Math.max(rect.y,Math.min(c.y,rect.y+rect.h));return (c.x-x)**2+(c.y-y)**2<c.r*c.r}
export function resolveCircle(c,rect){if(!circleRect(c,rect))return;let nx=c.x,ny=c.y;const cx=Math.max(rect.x,Math.min(c.x,rect.x+rect.w)),cy=Math.max(rect.y,Math.min(c.y,rect.y+rect.h));let dx=c.x-cx,dy=c.y-cy,dist=Math.hypot(dx,dy);if(dist>0){const push=c.r-dist;c.x+=dx/dist*push;c.y+=dy/dist*push}else{const dl=Math.abs(c.x-rect.x),dr=Math.abs(rect.x+rect.w-c.x),dt=Math.abs(c.y-rect.y),db=Math.abs(rect.y+rect.h-c.y),m=Math.min(dl,dr,dt,db);if(m===dl)c.x=rect.x-c.r;else if(m===dr)c.x=rect.x+rect.w+c.r;else if(m===dt)c.y=rect.y-c.r;else c.y=rect.y+rect.h+c.r}return {x:c.x-nx,y:c.y-ny}}
export function moveCircle(c,dx,dy,walls){c.x+=dx;for(const w of walls)resolveCircle(c,w);c.y+=dy;for(const w of walls)resolveCircle(c,w);c.x=Math.max(c.r,Math.min(960-c.r,c.x));c.y=Math.max(c.r,Math.min(540-c.r,c.y))}
export class Player{
 constructor(){this.r=15;this.speed=215;this.maxHp=100;this.hp=100;this.glow=62;this.maxGlow=100;this.pulseRadius=112;this.pulseCost=25;this.shardBonus=0;this.x=80;this.y=460;this.vx=0;this.vy=0;this.dashTime=0;this.dashCooldown=0;this.invuln=0;this.pulseTime=0;this.anim=0}
 reset(pos){this.x=pos.x;this.y=pos.y;this.hp=this.maxHp;this.glow=Math.min(this.maxGlow,this.glow+35);this.vx=this.vy=0;this.invuln=1;this.dashTime=0;this.dashCooldown=0}
 update(dt,input,walls){this.anim+=dt;this.invuln=Math.max(0,this.invuln-dt);this.dashCooldown=Math.max(0,this.dashCooldown-dt);this.pulseTime=Math.max(0,this.pulseTime-dt);let a=input.axis(),len=Math.hypot(a.x,a.y);if(len){this.vx+=(a.x*this.speed-this.vx)*Math.min(1,dt*12);this.vy+=(a.y*this.speed-this.vy)*Math.min(1,dt*12)}else{this.vx*=Math.pow(.05,dt);this.vy*=Math.pow(.05,dt)}if(input.consumeAction('dash')&&this.dashCooldown<=0&&this.glow>=12&&len){this.dashTime=.14;this.dashCooldown=1.0;this.glow-=12;this.vx=a.x*760;this.vy=a.y*760}if(this.dashTime>0)this.dashTime-=dt;moveCircle(this,this.vx*dt,this.vy*dt,walls)}
 hurt(amount,from){if(this.invuln>0)return false;this.hp-=amount;this.invuln=.75;const dx=this.x-from.x,dy=this.y-from.y,d=Math.hypot(dx,dy)||1;this.vx=dx/d*300;this.vy=dy/d*300;return true}
 applyUpgrade(id){if(id==='core'){this.maxHp+=20;this.hp=this.maxHp}else if(id==='swift'){this.speed*=1.16}else if(id==='nova'){this.pulseRadius+=30;this.pulseCost=Math.max(12,this.pulseCost-5)}else if(id==='collector'){this.shardBonus+=50;this.maxGlow+=20;this.glow=Math.min(this.maxGlow,this.glow+35)}}
 draw(ctx){const bob=Math.sin(this.anim*7)*1.5;ctx.save();ctx.translate(this.x,this.y+bob);if(this.pulseTime>0){ctx.globalAlpha=this.pulseTime/.3;ctx.strokeStyle='#a68cff';ctx.lineWidth=4;ctx.shadowBlur=25;ctx.shadowColor='#9e6dff';ctx.beginPath();ctx.arc(0,0,this.pulseRadius*(1-this.pulseTime/.3*.25),0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=this.invuln>0&&Math.floor(this.invuln*18)%2===0?.4:1;const g=ctx.createRadialGradient(0,0,2,0,0,35);g.addColorStop(0,'#fff');g.addColorStop(.18,'#a8ffff');g.addColorStop(.55,'#45c9ff');g.addColorStop(1,'rgba(57,128,255,0)');ctx.fillStyle=g;ctx.shadowBlur=28;ctx.shadowColor='#55eaff';ctx.beginPath();ctx.arc(0,0,35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eaffff';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(0,0,this.r,0,Math.PI*2);ctx.fill();ctx.restore()}
}
export class Ghost{
 constructor(pos,type,level){this.x=pos.x;this.y=pos.y;this.r=type==='brute'?21: type==='dart'?11:16;this.type=type;this.level=level;this.hp=type==='brute'?2:1;this.hit=0;this.anim=Math.random()*6;this.speed=(type==='brute'?48:type==='dart'?112:72)+level*7}
 update(dt,player,walls){this.anim+=dt;this.hit=Math.max(0,this.hit-dt);let dx=player.x-this.x,dy=player.y-this.y,d=Math.hypot(dx,dy)||1;let tx=dx/d,ty=dy/d;if(this.type==='dart'){const sway=Math.sin(this.anim*5)*.35;tx+=-ty*sway;ty+=dx/d*sway;const l=Math.hypot(tx,ty);tx/=l;ty/=l}moveCircle(this,tx*this.speed*dt,ty*this.speed*dt,walls)}
 damage(){this.hp--;this.hit=.15;return this.hp<=0}
 draw(ctx){ctx.save();ctx.translate(this.x,this.y+Math.sin(this.anim*4)*2);const col=this.type==='brute'?'#ff5e9e':this.type==='dart'?'#ffbd65':'#a875ff';ctx.globalAlpha=this.hit>0?.55:1;ctx.shadowBlur=22;ctx.shadowColor=col;ctx.fillStyle=col;ctx.beginPath();ctx.arc(0,0,this.r,Math.PI,0);ctx.lineTo(this.r*.75,this.r*.85);ctx.lineTo(this.r*.25,this.r*.55);ctx.lineTo(0,this.r*.9);ctx.lineTo(-this.r*.25,this.r*.55);ctx.lineTo(-this.r*.75,this.r*.85);ctx.closePath();ctx.fill();ctx.fillStyle='#161137';ctx.shadowBlur=0;ctx.beginPath();ctx.arc(-this.r*.35,-2,2.5,0,Math.PI*2);ctx.arc(this.r*.35,-2,2.5,0,Math.PI*2);ctx.fill();ctx.restore()}
}
export class Shard{constructor(pos,i){this.x=pos.x;this.y=pos.y;this.r=9;this.i=i;this.t=Math.random()*6;this.collected=false}update(dt){this.t+=dt}draw(ctx){if(this.collected)return;ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.t);ctx.shadowBlur=22;ctx.shadowColor='#62f8ff';ctx.fillStyle='#79ffff';ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(8,0);ctx.lineTo(0,12);ctx.lineTo(-8,0);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-2,-3,2,0,Math.PI*2);ctx.fill();ctx.restore()}}