import {Input} from './input.js';
import {AudioEngine} from './audio.js';
import {ParticleSystem} from './particles.js';
import {Player,Ghost,Shard,circleHit} from './entities.js';
import {createLevel} from './levels.js';
import {UI} from './ui.js';

const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=960,H=540;
class Game{
 constructor(){this.input=new Input(canvas,document.getElementById('stick-area'),document.getElementById('stick-knob'));this.audio=new AudioEngine();this.particles=new ParticleSystem();this.ui=new UI();this.state='title';this.level=1;this.score=0;this.shake=0;this.flash=0;this.hitStop=0;this.last=performance.now();this.acc=0;this.player=new Player();this.world=null;this.ghosts=[];this.shards=[];this.bindUI();requestAnimationFrame(t=>this.frame(t))}
 bindUI(){this.ui.on('start',()=>{this.audio.resume();this.audio.click();this.begin()});this.ui.on('restart',()=>{this.audio.resume();this.audio.click();this.begin()});this.ui.on('menu',()=>{this.audio.click();this.state='title';this.ui.state('title')});this.ui.on('pause',()=>{if(this.state==='playing'){this.audio.click();this.state='pause';this.ui.state('pause')}});this.ui.on('resume',()=>{this.audio.click();this.state='playing';this.ui.state('playing')});this.ui.on('upgrade',id=>{this.audio.click();this.player.applyUpgrade(id);this.level++;this.loadLevel();this.state='playing';this.ui.state('playing')})}
 begin(){this.level=1;this.score=0;this.player=new Player();this.loadLevel();this.state='playing';this.ui.state('playing')}
 loadLevel(){this.world=createLevel(this.level);this.player.reset(this.world.start);this.ghosts=this.world.ghosts.map(g=>new Ghost(g.p,g.type,this.level));this.shards=this.world.shards.map((p,i)=>new Shard(p,i));this.ui.update(this.player,this.level,0,this.shards.length,this.score);this.particles.burst(this.world.start.x,this.world.start.y,'#66eaff',22,120);this.shake=.18}
 frame(now){let dt=Math.min(.1,(now-this.last)/1000);this.last=now;this.acc+=dt;while(this.acc>=1/60){this.tick(1/60);this.acc-=1/60}this.render();requestAnimationFrame(t=>this.frame(t))}
 tick(dt){if(this.input.consumeKey('Escape')){if(this.state==='playing'){this.state='pause';this.ui.state('pause')}else if(this.state==='pause'){this.state='playing';this.ui.state('playing')}}if(this.state!=='playing')return;if(this.hitStop>0){this.hitStop-=dt;return}this.shake=Math.max(0,this.shake-dt);this.flash=Math.max(0,this.flash-dt);this.player.update(dt,this.input,this.world.walls);for(const s of this.shards)s.update(dt);for(const g of this.ghosts)g.update(dt,this.player,this.world.walls);this.handlePulse();this.collectShards();this.handleGhosts();this.particles.update(dt);const got=this.shards.filter(s=>s.collected).length;if(got===this.shards.length&&circleHit(this.player,{x:this.world.exit.x,y:this.world.exit.y,r:25}))this.clearLevel();this.ui.update(this.player,this.level,got,this.shards.length,this.score);if(this.player.hp<=0)this.die()}
 handlePulse(){if(!(this.input.consumeAction('pulse')||this.input.consumeMousePulse()))return;if(this.player.glow<this.player.pulseCost||this.player.pulseTime>0)return;this.player.glow-=this.player.pulseCost;this.player.pulseTime=.3;this.audio.pulse();this.particles.ring(this.player.x,this.player.y,'#a778ff',30);let hit=0;for(const g of this.ghosts){if(Math.hypot(g.x-this.player.x,g.y-this.player.y)<this.player.pulseRadius+g.r){hit++;const dead=g.damage();const dx=g.x-this.player.x,dy=g.y-this.player.y,d=Math.hypot(dx,dy)||1;g.x+=dx/d*28;g.y+=dy/d*28;this.particles.burst(g.x,g.y,'#d181ff',dead?18:7,170);if(dead){this.score+=100;g.dead=true}}}this.ghosts=this.ghosts.filter(g=>!g.dead);if(hit){this.shake=.16;this.hitStop=.055}}
 collectShards(){for(const s of this.shards){if(!s.collected&&circleHit(this.player,s)){s.collected=true;this.player.glow=Math.min(this.player.maxGlow,this.player.glow+23);this.score+=150+this.player.shardBonus;this.audio.collect();this.particles.burst(s.x,s.y,'#65f7ff',20,150);this.particles.ring(s.x,s.y,'#65f7ff',10);this.shake=.08}}}
 handleGhosts(){for(const g of this.ghosts){if(circleHit(this.player,g)&&this.player.hurt(g.type==='brute'?23:14,g)){this.audio.hit();this.particles.burst(this.player.x,this.player.y,'#ff639d',18,160);this.flash=.12;this.shake=.25;this.hitStop=.07}}}
 clearLevel(){if(this.state!=='playing')return;this.score+=this.level*500;this.particles.burst(this.world.exit.x,this.world.exit.y,'#8dffda',38,220);this.audio.collect();if(this.level>=6){this.win();return}const opts=[{id:'core',icon:'♥',name:'RADIANT CORE',desc:'+20 maximum vitality and fully heal.'},{id:'swift',icon:'➤',name:'SWIFT CURRENT',desc:'Move 16% faster. A clean escape is a skill.'},{id:'nova',icon:'✹',name:'PULSE BLOOM',desc:'+30 pulse radius and -5 glow cost.'},{id:'collector',icon:'✦',name:'GREEDY LIGHT',desc:'Shards score +50, max glow +20.'}];const chosen=[opts[(this.level-1)%4],opts[(this.level+1)%4],opts[(this.level+2)%4]];this.state='upgrade';this.ui.showUpgrade(chosen)}
 die(){if(this.state!=='playing')return;this.state='gameover';this.audio.hit();this.particles.burst(this.player.x,this.player.y,'#ff4f8d',45,250);const best=this.ui.setBest(this.score);this.ui.showGameOver(this.score,best)}
 win(){this.state='win';const best=this.ui.setBest(this.score);this.ui.showWin(this.score,best)}
 render(){ctx.clearRect(0,0,W,H);if(!this.world){this.drawTitleBackdrop();return}ctx.save();if(this.shake>0)ctx.translate((Math.random()-.5)*this.shake*28,(Math.random()-.5)*this.shake*28);this.drawWorld();ctx.restore();if(this.flash>0){ctx.fillStyle=`rgba(255,100,160,${this.flash*2})`;ctx.fillRect(0,0,W,H)}}
 drawTitleBackdrop(){const g=ctx.createRadialGradient(480,280,10,480,280,600);g.addColorStop(0,'#171b52');g.addColorStop(1,'#050716');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<35;i++){const x=(i*173)%W,y=(i*79)%H;ctx.fillStyle=`rgba(100,220,255,${.15+(i%4)*.08})`;ctx.beginPath();ctx.arc(x,y,1+(i%3),0,7);ctx.fill()}}
 drawWorld(){const bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,'#080d2d');bg.addColorStop(.55,'#0b1238');bg.addColorStop(1,'#170b31');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);for(const s of this.world.stars){ctx.globalAlpha=s.a;ctx.fillStyle='#a8dfff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle='rgba(82,135,202,.08)';ctx.lineWidth=1;for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const w of this.world.walls){ctx.save();ctx.fillStyle='#141a45';ctx.shadowBlur=15;ctx.shadowColor='#273985';ctx.fillRect(w.x,w.y,w.w,w.h);ctx.strokeStyle='#394c91';ctx.strokeRect(w.x+.5,w.y+.5,w.w-1,w.h-1);ctx.restore()}this.drawExit();for(const s of this.shards)s.draw(ctx);for(const g of this.ghosts)g.draw(ctx);this.player.draw(ctx);this.particles.draw(ctx);const grad=ctx.createRadialGradient(W/2,H/2,170,W/2,H/2,620);grad.addColorStop(0,'transparent');grad.addColorStop(1,'rgba(0,0,8,.52)');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H)}
 drawExit(){const open=this.shards.every(s=>s.collected),p=1+Math.sin(performance.now()/280)*.12;ctx.save();ctx.translate(this.world.exit.x,this.world.exit.y);ctx.rotate(Math.PI/4);ctx.shadowBlur=26;ctx.shadowColor=open?'#75ffce':'#53679c';ctx.strokeStyle=open?'#75ffce':'#52638f';ctx.lineWidth=4;ctx.strokeRect(-17*p,-17*p,34*p,34*p);ctx.rotate(-Math.PI/4);ctx.fillStyle=open?'rgba(117,255,206,.18)':'rgba(70,87,140,.15)';ctx.beginPath();ctx.arc(0,0,27*p,0,7);ctx.fill();ctx.fillStyle=open?'#baffeb':'#8893bf';ctx.font='bold 9px Arial';ctx.textAlign='center';ctx.fillText(open?'EXIT':'LOCKED',0,43);ctx.restore()}
}
new Game();