export class UI{
 constructor(){this.panels={title:document.getElementById('title-panel'),pause:document.getElementById('pause-panel'),upgrade:document.getElementById('upgrade-panel'),gameover:document.getElementById('gameover-panel'),win:document.getElementById('win-panel')};this.overlay=document.getElementById('overlay');this.hud=document.getElementById('hud');this.best=Number(localStorage.getItem('gloraBest')||0);this.callbacks={};this.bind('start-button','start');this.bind('resume-button','resume');this.bind('pause-menu-button','menu');this.bind('restart-button','restart');this.bind('gameover-menu-button','menu');this.bind('win-button','restart');this.bind('win-menu-button','menu');document.getElementById('pause-button').onclick=()=>this.fire('pause');this.setBestText()}
 bind(id,ev){document.getElementById(id).onclick=()=>this.fire(ev)} on(ev,fn){this.callbacks[ev]=fn} fire(ev,data){if(this.callbacks[ev])this.callbacks[ev](data)} setBestText(){document.getElementById('title-best').textContent=this.best.toLocaleString()}
 hideAll(){Object.values(this.panels).forEach(p=>p.classList.add('hidden'))}
 state(s){this.hideAll();this.hud.classList.toggle('hidden',s==='title'||s==='gameover'||s==='win');if(s==='title')this.panels.title.classList.remove('hidden');if(s==='pause')this.panels.pause.classList.remove('hidden');if(s==='upgrade')this.panels.upgrade.classList.remove('hidden')}
 showGameOver(score,best){this.hideAll();this.hud.classList.add('hidden');document.getElementById('gameover-score').textContent=score.toLocaleString();document.getElementById('gameover-best').textContent=best.toLocaleString();this.panels.gameover.classList.remove('hidden')}
 showWin(score,best){this.hideAll();this.hud.classList.add('hidden');document.getElementById('win-score').textContent=score.toLocaleString();document.getElementById('win-best').textContent=best.toLocaleString();this.panels.win.classList.remove('hidden')}
 showUpgrade(options){const box=document.getElementById('upgrade-options');box.innerHTML='';options.forEach(o=>{const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<div class="upgrade-icon">${o.icon}</div><h3>${o.name}</h3><p>${o.desc}</p>`;b.onclick=()=>this.fire('upgrade',o.id);box.appendChild(b)});this.state('upgrade')}
 update(p,level,got,total,score){document.getElementById('level-value').textContent=level;document.getElementById('health-bar').style.width=Math.max(0,p.hp/p.maxHp*100)+'%';document.getElementById('glow-bar').style.width=Math.max(0,p.glow/p.maxGlow*100)+'%';document.getElementById('shard-value').textContent=`✦ ${got} / ${total}`;document.getElementById('score-value').textContent=String(score).padStart(6,'0')}
 setBest(score){if(score>this.best){this.best=score;localStorage.setItem('gloraBest',this.best);this.setBestText()}return this.best}
}