const TAU=Math.PI*2;
export function circleHit(a,b){return Math.hypot(a.x-b.x,a.y-b.y)<a.r+b.r;}
export class Player {
  constructor(x,y){this.x=x;this.y=y;this.r=17;this.vx=0;this.vy=0;this.angle=0;this.hp=100;this.maxHp=100;this.speed=330;this.accel=1700;this.fireRate=.22;this.fireTimer=0;this.damage=18;this.multishot=1;this.invuln=0;this.shield=0;}
  update(dt,g){const m=g.input.movement();this.vx+=m.x*this.accel*dt;this.vy+=m.y*this.accel*dt;const drag=Math.pow(.0008,dt);this.vx*=drag;this.vy*=drag;const v=Math.hypot(this.vx,this.vy);if(v>this.speed){this.vx=this.vx/v*this.speed;this.vy=this.vy/v*this.speed;}this.x=Math.max(this.r,Math.min(g.W-this.r,this.x+this.vx*dt));this.y=Math.max(82+this.r,Math.min(g.H-this.r,this.y+this.vy*dt));const a=g.input.aim(this);this.angle=Math.atan2(a.y-this.y,a.x-this.x);this.fireTimer-=dt;this.invuln-=dt;if(g.input.firing()&&this.fireTimer<=0){this.fireTimer=this.fireRate;this.fire(g);}}
  fire(g){const spread=.14;for(let i=0;i<this.multishot;i++){const offset=(i-(this.multishot-1)/2)*spread;const a=this.angle+offset;g.bullets.push(new Bullet(this.x+Math.cos(a)*24,this.y+Math.sin(a)*24,a,650,this.damage,4));}g.audio.shoot();g.particles.spark(this.x+Math.cos(this.angle)*22,this.y+Math.sin(this.angle)*22,'#8ffff0',3);}
  hurt(amount,g){if(this.invuln>0)return; if(this.shield>0){this.shield--;g.particles.burst(this.x,this.y,'#73a4ff',16,180);g.audio.hit();this.invuln=.35;return;}this.hp-=amount;this.invuln=.8;g.flash=.16;g.shake=10;g.audio.hurt();g.particles.burst(this.x,this.y,'#ff5f91',18,200);if(this.hp<=0)g.end(false);}
  draw(ctx){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.angle);ctx.globalAlpha=this.invuln>0&&Math.floor(this.invuln*16)%2? .35:1;ctx.shadowBlur=25;ctx.shadowColor='#74f5e0';ctx.fillStyle='#73f5e2';ctx.beginPath();ctx.moveTo(25,0);ctx.lineTo(-13,-14);ctx.lineTo(-8,0);ctx.lineTo(-13,14);ctx.closePath();ctx.fill();ctx.fillStyle='#eefeff';ctx.shadowBlur=8;ctx.beginPath();ctx.arc(4,0,5,0,TAU);ctx.fill();ctx.restore();if(this.shield>0){ctx.strokeStyle='#78a9ff';ctx.globalAlpha=.55;ctx.lineWidth=2;ctx.beginPath();ctx.arc(this.x,this.y,25,0,TAU);ctx.stroke();ctx.globalAlpha=1;}}
}
export class Bullet {
  constructor(x,y,a,speed,damage,r=4){this.x=x;this.y=y;this.vx=Math.cos(a)*speed;this.vy=Math.sin(a)*speed;this.damage=damage;this.r=r;this.life=1.3;this.dead=false;}
  update(dt,g){this.x+=this.vx*dt;this.y+=this.vy*dt;this.life-=dt;if(this.life<=0||this.x<-30||this.x>g.W+30||this.y<60||this.y>g.H+30)this.dead=true;}
  draw(ctx){ctx.strokeStyle='#9ffff0';ctx.lineWidth=3;ctx.shadowBlur=14;ctx.shadowColor='#44e5d2';ctx.beginPath();ctx.moveTo(this.x-this.vx*.018,this.y-this.vy*.018);ctx.lineTo(this.x,this.y);ctx.stroke();ctx.shadowBlur=0;}
}
export class EnemyShot extends Bullet { constructor(x,y,a,s=230,d=10){super(x,y,a,s,d,5);this.life=4;} draw(ctx){ctx.fillStyle='#ff668d';ctx.shadowBlur=14;ctx.shadowColor='#ff668d';ctx.beginPath();ctx.arc(this.x,this.y,5,0,TAU);ctx.fill();ctx.shadowBlur=0;} }
export class Pickup {
  constructor(x,y){this.x=x;this.y=y;this.r=10;this.life=10;this.t=0;}
  update(dt,g){this.t+=dt;this.life-=dt;if(circleHit(this,g.player)){this.dead=true;g.player.hp=Math.min(g.player.maxHp,g.player.hp+12);g.score+=50;g.particles.burst(this.x,this.y,'#ffd56e',18,150);g.particles.text(this.x,this.y-15,'+12 CORE','#ffd56e');g.audio.pickup();}if(this.life<=0)this.dead=true;}
  draw(ctx){const s=1+Math.sin(this.t*6)*.15;ctx.save();ctx.translate(this.x,this.y);ctx.scale(s,s);ctx.rotate(this.t);ctx.fillStyle='#ffd56e';ctx.shadowBlur=18;ctx.shadowColor='#ffd56e';ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(8,0);ctx.lineTo(0,10);ctx.lineTo(-8,0);ctx.closePath();ctx.fill();ctx.restore();}
}
export class Enemy {
  constructor(type,x,y,wave){this.type=type;this.x=x;this.y=y;this.wave=wave;this.dead=false;this.phase=Math.random()*TAU;this.shotTimer=1+Math.random();this.r=17;this.speed=90;this.hp=35+wave*9;this.maxHp=this.hp;this.color='#ff5e91';if(type==='shooter'){this.r=16;this.speed=70;this.hp=45+wave*10;this.color='#b477ff';}if(type==='brute'){this.r=27;this.speed=45;this.hp=145+wave*28;this.color='#ff9c62';}if(type==='splitter'){this.r=22;this.speed=60;this.hp=80+wave*15;this.color='#ffdc69';}if(type==='mini'){this.r=10;this.speed=160;this.hp=18+wave*4;this.color='#ff7ab1';}if(type==='boss'){this.r=48;this.speed=38;this.hp=900+wave*160;this.maxHp=this.hp;this.color='#ff447e';this.shotTimer=1.2;}}
  update(dt,g){const dx=g.player.x-this.x,dy=g.player.y-this.y,d=Math.hypot(dx,dy)||1;let ax=dx/d,ay=dy/d;if(this.type==='shooter'){const desired=250;const toward=(d-desired)*.012;ax=dx/d*toward+Math.cos(this.phase+g.time)*.45;ay=dy/d*toward+Math.sin(this.phase+g.time)*.45;this.shotTimer-=dt;if(this.shotTimer<=0){this.shotTimer=1.8-Math.min(.8,this.wave*.06);g.enemyShots.push(new EnemyShot(this.x,this.y,Math.atan2(dy,dx),190+g.wave*8,9+g.wave));g.audio.hit();}}else if(this.type==='boss'){this.shotTimer-=dt;ax=dx/d*.5+Math.cos(g.time*.7)*.6;ay=dy/d*.5+Math.sin(g.time*.7)*.6;if(this.shotTimer<=0){this.shotTimer=1.05;for(let i=0;i<8;i++)g.enemyShots.push(new EnemyShot(this.x,this.y,i*Math.PI/4+g.time*.3,150+g.wave*5,12));g.particles.burst(this.x,this.y,'#ff447e',12,100);}}this.x+=ax*this.speed*dt;this.y+=ay*this.speed*dt;this.x=Math.max(this.r,Math.min(g.W-this.r,this.x));this.y=Math.max(84+this.r,Math.min(g.H-this.r,this.y));if(circleHit(this,g.player))g.player.hurt(this.type==='boss'?24:this.type==='brute'?18:10,g);}
  hit(damage,g){this.hp-=damage;g.particles.spark(this.x,this.y,this.color,4);g.shake=Math.max(g.shake,3);if(this.hp<=0){g.killEnemy(this);}}
  draw(ctx){ctx.save();ctx.translate(this.x,this.y);ctx.rotate(this.phase+performance.now()*.0003);ctx.fillStyle=this.color;ctx.shadowBlur=this.type==='boss'?30:16;ctx.shadowColor=this.color;ctx.beginPath();const n=this.type==='boss'?10:this.type==='brute'?6:4;for(let i=0;i<n;i++){const a=i*TAU/n;const rr=i%2?this.r*.72:this.r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fill();ctx.fillStyle='#160f30';ctx.beginPath();ctx.arc(0,0,this.r*.3,0,TAU);ctx.fill();ctx.restore();if(this.type==='boss'||this.hp<this.maxHp){ctx.fillStyle='#241735';ctx.fillRect(this.x-this.r,this.y-this.r-12,this.r*2,3);ctx.fillStyle=this.color;ctx.fillRect(this.x-this.r,this.y-this.r-12,this.r*2*Math.max(0,this.hp/this.maxHp),3);}}
}