import { Input } from './input.js';
import { AudioManager } from './audio.js';
import { ParticleSystem } from './particles.js';
import { Player, Enemy, EnemyShot, Pickup, circleHit } from './entities.js';
import { WaveDirector, upgradeChoices } from './levels.js';
import { UI } from './ui.js';

const STATE={MENU:'menu',PLAYING:'playing',PAUSED:'pause',UPGRADE:'upgrade',GAMEOVER:'gameover',WIN:'win'};
class Game {
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.W=1000;this.H=650;this.input=new Input(canvas);this.audio=new AudioManager();this.particles=new ParticleSystem();this.ui=new UI();this.director=new WaveDirector();this.state=STATE.MENU;this.time=0;this.acc=0;this.last=performance.now();this.stars=Array.from({length:100},()=>({x:Math.random()*this.W,y:65+Math.random()*(this.H-65),r:.5+Math.random()*1.7,a:.2+Math.random()*.65,s:8+Math.random()*20}));this.bindUI();this.frame=this.frame.bind(this);requestAnimationFrame(this.frame);}
  bindUI(){this.ui.onStart=()=>{this.audio.init();this.start();};this.ui.onRetry=()=>{this.audio.init();this.start();};this.ui.onResume=()=>{this.state=STATE.PLAYING;this.ui.show('playing');this.audio.ui();};this.ui.onMenu=()=>{this.state=STATE.MENU;this.ui.show('menu');this.audio.ui();};this.ui.pauseCallback=()=>this.togglePause();window.addEventListener('keydown',e=>{if(e.key==='Escape'||e.key.toLowerCase()==='p')this.togglePause();if(this.state===STATE.UPGRADE&&['1','2','3'].includes(e.key)){this.chooseUpgrade(Number(e.key)-1);}});}
  start(){this.state=STATE.PLAYING;this.time=0;this.wave=1;this.score=0;this.shake=0;this.flash=0;this.hitStop=0;this.player=new Player(this.W/2,this.H/2+60);this.enemies=[];this.bullets=[];this.enemyShots=[];this.pickups=[];this.director.start(this.wave);this.upgradeList=[];this.ui.show('playing');this.audio.ui();this.particles.burst(this.player.x,this.player.y,'#7ff8e6',28,220);}
  togglePause(){if(this.state===STATE.PLAYING){this.state=STATE.PAUSED;this.ui.show('pause');this.audio.ui();}else if(this.state===STATE.PAUSED){this.state=STATE.PLAYING;this.ui.show('playing');this.audio.ui();}}
  update(dt){this.time+=dt;this.audio.update(dt,this.state===STATE.PLAYING);this.particles.update(dt);if(this.shake>0)this.shake*=Math.pow(.025,dt);if(this.flash>0)this.flash-=dt;if(this.state!==STATE.PLAYING)return;if(this.hitStop>0){this.hitStop-=dt;return;}this.player.update(dt,this);this.director.update(dt,this);for(const e of this.enemies)e.update(dt,this);for(const b of this.bullets)b.update(dt,this);for(const b of this.enemyShots)b.update(dt,this);for(const p of this.pickups)p.update(dt,this);this.resolveCollisions();this.enemies=this.enemies.filter(e=>!e.dead);this.bullets=this.bullets.filter(b=>!b.dead);this.enemyShots=this.enemyShots.filter(b=>!b.dead);this.pickups=this.pickups.filter(p=>!p.dead);if(this.director.done&&this.enemies.length===0){if(this.wave>=6)this.end(true);else this.openUpgrade();}this.ui.updateHud(this);}
  resolveCollisions(){for(const b of this.bullets){if(b.dead)continue;for(const e of this.enemies){if(!e.dead&&circleHit(b,e)){b.dead=true;e.hit(b.damage,this);this.score+=5;break;}}}for(const b of this.enemyShots){if(!b.dead&&circleHit(b,this.player)){b.dead=true;this.player.hurt(b.damage,this);}}}
  killEnemy(e){if(e.dead)return;e.dead=true;const gain=e.type==='boss'?1200:e.type==='brute'?180:e.type==='splitter'?130:70;this.score+=gain;this.shake=Math.max(this.shake,e.type==='boss'?16:6);this.flash=e.type==='boss'?.1:.035;this.hitStop=e.type==='boss'?.06:.025;this.audio.hit();this.particles.burst(e.x,e.y,e.color,e.type==='boss'?55:18,e.type==='boss'?270:170);this.particles.text(e.x,e.y-20,`+${gain}`,'#ffd77a');if(Math.random()<.18||e.type==='boss')this.pickups.push(new Pickup(e.x,e.y));if(e.type==='splitter')for(let i=0;i<2;i++)this.enemies.push(new Enemy('mini',e.x+(i?14:-14),e.y,e.wave));}
  openUpgrade(){this.state=STATE.UPGRADE;this.upgradeList=upgradeChoices(this.wave);this.ui.upgrade(this.upgradeList);this.ui.show('upgrade');this.audio.upgrade();this.particles.burst(this.player.x,this.player.y,'#ffd56e',30,180);}
  chooseUpgrade(i){if(this.state!==STATE.UPGRADE||!this.upgradeList[i])return;this.upgradeList[i].apply(this.player);this.particles.text(this.player.x,this.player.y-30,this.upgradeList[i].name,'#7ff8e6');this.audio.ui();this.wave++;this.director.start(this.wave);this.state=STATE.PLAYING;this.ui.show('playing');}
  end(won){this.state=won?STATE.WIN:STATE.GAMEOVER;this.ui.result(this.score,won);this.ui.show(won?'win':'gameover');this.audio.tone(won?740:55,.5,won?'triangle':'sawtooth',.25,won?1.8:.3);if(won)this.particles.burst(this.player.x,this.player.y,'#ffd56e',80,310);else this.particles.burst(this.player.x,this.player.y,'#ff5f91',70,280);}
  draw(){const c=this.ctx;c.clearRect(0,0,this.W,this.H);const bg=c.createLinearGradient(0,0,0,this.H);bg.addColorStop(0,'#090d29');bg.addColorStop(1,'#050713');c.fillStyle=bg;c.fillRect(0,0,this.W,this.H);c.save();const sx=(Math.random()-.5)*this.shake,sy=(Math.random()-.5)*this.shake;c.translate(sx,sy);this.drawArena(c);for(const p of this.pickups)p.draw(c);for(const b of this.bullets)b.draw(c);for(const b of this.enemyShots)b.draw(c);for(const e of this.enemies)e.draw(c);if(this.player&&this.state!==STATE.MENU)this.player.draw(c);this.particles.draw(c);c.restore();if(this.flash>0){c.fillStyle=`rgba(255,255,255,${this.flash*2})`;c.fillRect(0,0,this.W,this.H);}if(this.state===STATE.PLAYING&&this.input.hasTouch)this.drawTouch(c);}
  drawArena(c){c.save();c.strokeStyle='rgba(93,117,210,.09)';c.lineWidth=1;const offset=(this.time*12)%40;for(let x=-40+offset;x<this.W+40;x+=40){c.beginPath();c.moveTo(x,65);c.lineTo(x,this.H);c.stroke();}for(let y=65+offset;y<this.H;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(this.W,y);c.stroke();}for(const s of this.stars){c.globalAlpha=s.a*(.7+.3*Math.sin(this.time*s.s/20+s.x));c.fillStyle='#b8c9ff';c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();}c.globalAlpha=1;c.strokeStyle='rgba(111,245,224,.15)';c.lineWidth=2;c.strokeRect(12,75,this.W-24,this.H-87);c.restore();}
  drawTouch(c){c.globalAlpha=.32;c.strokeStyle='#9caeff';c.lineWidth=2;c.beginPath();c.arc(120,530,55,0,Math.PI*2);c.stroke();c.beginPath();c.arc(120,530,22,0,Math.PI*2);c.stroke();c.beginPath();c.arc(875,530,48,0,Math.PI*2);c.stroke();c.fillStyle='#b5c5ff';c.font='10px Arial';c.textAlign='center';c.fillText('MOVE',120,605);c.fillText('AIM / FIRE',875,605);c.globalAlpha=1;}
  frame(now){let dt=Math.min(.1,(now-this.last)/1000);this.last=now;this.acc+=dt;while(this.acc>=1/60){this.update(1/60);this.acc-=1/60;}this.draw();requestAnimationFrame(this.frame);}
}
new Game(document.querySelector('#game'));